spring.application.name=backend

# Conectar com o banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/zotion_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always


# Configurações das chaves RSA para JWT
jwt.public.key=classpath:certs/key.pub
jwt.private.key=classpath:certs/key.priv

