spring.application.name=backend

# Conectar com o banco de dados PostgreSQL
#Configurações para o PostreSQL

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/zotion-db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update

#Dados para as chaves RSA
#Gerei via gerador online de chaves RSA de 2048 bits
#Como projeto publico, deixei essas chaves disponiveis aqui no github mesmo
#Em um projeto real, essas chaves devem ser mantidas em local seguro e nunca expostas publicamente!!

jwt.private.key=classpath:certs/app.key
jwt.public.key=classpath:certs/app.pub


#Configurações do serviço da LLM (Estou usando o Gemini)
#A chave da API deve ser definida no .env na raiz do projeto. Aqui estou apenas declarando a variável para o Spring. 

gemini.api.key=${GEMINI_API_KEY}

# Adicionei para garantir que o swagger use o caminho certo pelo NGINX :D
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs
server.forward-headers-strategy=framework
