spring.application.name=backend

# Conectar com o banco de dados PostgreSQL



# Configurações das chaves RSA para JWT
jwt.public.key=classpath:certs/key.pub
jwt.private.key=classpath:certs/key.priv

